version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=travel_go

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - --mnemonic="test test test test test test test test test test test junk"
      - --networkId=1337
      - --chain.vmErrorsOnRPCResponse=true

volumes:
  mongodb_data: 